### ISSUE TITLE
Server is crashed when downloading quite large file

### ISSUE THREAD

**Issue by yegor86** [yegor86/my-cloud-client#36]
When downloading a large file, e.g. image, the server is crashed with following error message:
"Error: Can't set headers after they are sent." , which crash the server
```bash
GET /files/download/masdeft@gmail.com/shared_folder/ACP-8927.png 200 647.135 ms - 3472
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (c:\projects\my-cloud-client\node_modules\express\lib\response.js:662:10)
    at ServerResponse.send (c:\projects\my-cloud-client\node_modules\express\lib\response.js:159:10)
    at IncomingMessage.<anonymous> (c:\projects\my-cloud-client\server\routes\download.js:24:36)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at IncomingMessage.Readable.push (_stream_readable.js:110:10)
    at HTTPParser.parserOnBody (_http_common.js:109:22)
    at Socket.socketOnData (_http_client.js:305:20)
28 Jan 17:54:49 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by yegor86** [comment]
Attaching example of file which cause server crash while downloading

![test](https://cloud.githubusercontent.com/assets/487676/12652694/acc71be2-c5f4-11e5-8f5b-175b71327dfc.png)
