### ISSUE TITLE
Upload File: Frontend stops working if Backend is down

### ISSUE THREAD

**Issue by yegor86** [yegor86/my-cloud-client#6]
Cloud Client no longer responds after uploading a file when Backend is down
The error message is as follows
```bash
Error: connect ECONNREFUSED 127.0.0.1:3030
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
24 Nov 19:53:58 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by yegor86** [comment]
Cannot reproduce now.
Closing...
